name: kadena_dart_sdk
description: A dart package for interacting with the Kadena blockchain.
version: 2.3.3
repository: https://github.com/Eucalyptus-Labs/KadenaDartSdk

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  blake2b: ^0.2.2
  hex: ^0.2.0
  pinenacl: ^0.5.1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6

flutter:
